# Your first steps with Julia

## Przemysław Szufel

In [ ]:
# Ctrl + ENTER
versioninfo()

In [ ]:
pwd()

In [ ]:
]st

In [ ]:
;ls -la

In [ ]:
function f(x,y) 
    x+y
end 

f(x,y) = x+y

In [ ]:
f(5,12)

In [ ]:
@code_lowered f(5,6)

In [ ]:
@code_typed f(4,5)

In [ ]:
@code_llvm f(5,6)

In [ ]:
@code_native f(5,6)

In [ ]:
@code_native f(5.1,6)

In [83]:
v = [1,2,3,4]

4-element Vector{Int64}:
 1
 2
 3
 4

In [84]:
v3 = [ 3x for x in 1:9] #Python range(1,10)

9-element Vector{Int64}:
  3
  6
  9
 12
 15
 18
 21
 24
 27

In [86]:
v3[1:4]

4-element Vector{Int64}:
  3
  6
  9
 12

In [87]:
v₄= [ √x₁ for x₁ ∈ 1:9] 

9-element Vector{Float64}:
 1.0
 1.4142135623730951
 1.7320508075688772
 2.0
 2.23606797749979
 2.449489742783178
 2.6457513110645907
 2.8284271247461903
 3.0

In [88]:
typeof(v₄)

Vector{Float64} (alias for Array{Float64, 1})

In [89]:
eltype(v₄)

Float64

In [91]:
b = Int[]
append!(b, 5)

1-element Vector{Int64}:
 5

In [92]:
c = []

Any[]

In [93]:
c = Complex(1,4)

1 + 4im

In [94]:
typeof(c)

Complex{Int64}

In [95]:
dump(c)

Complex{Int64}
  re: Int64 1
  im: Int64 4


In [96]:
c2=Complex{Float64}(1,4)

1.0 + 4.0im

In [97]:
typeof(c2)

ComplexF64 (alias for Complex{Float64})

In [98]:
c2=Complex{Float32}(1,4)
typeof(c2)

ComplexF32 (alias for Complex{Float32})

In [99]:
x = 1//2 + 1//4

3//4

In [100]:
typeof(x)

Rational{Int64}

In [101]:
c3=Complex{Rational{Int128}}(1//4,4)
typeof(c3)

Complex{Rational{Int128}}

### Data types

In [102]:
parse(Float64, "3.7")

3.7

In [103]:
one(Float64), zero(UInt32)

(1.0, 0x00000000)

In [104]:
@show Int64('a') 	# character to integer
@show Int64(2.0) 	# float to integer
#Int64(1.3) 		# inexact error
#Int64("a") 		# error no conversion possible
@show Float64(1) 	# integer to float
@show Bool(1) 		# boolean true
@show Bool(0) 		# boolean false
@show Char(89) 		# integer to char
@show zero(10.0) 	# zero of  arg type (Float64)
@show one(Int64) 	# one of type Int64
@show convert(Int64, 1.0)	# float to integer
@show parse(Int64, "1") 

Int64('a') = 97
Int64(2.0) = 2
Float64(1) = 1.0
Bool(1) = true
Bool(0) = false
Char(89) = 'Y'
zero(10.0) = 0.0
one(Int64) = 1
convert(Int64, 1.0) = 1
parse(Int64, "1") = 1


1

In [ ]:
@show Int <: Any
@show Int <: Union{Int, Float64}
@show typeof(nothing)

In [ ]:
f(x) = println("x= $x ")
res = f(1)
typeof(res)

In [105]:
π

π = 3.1415926535897...

In [106]:
typeof(π)

Irrational{:π}

In [116]:
setprecision(10000)
@show BigFloat(π);

BigFloat(π) = 3.141592653589793238462643383279502884197169399375105820974944592307816406286208998628034825342117067982148086513282306647093844609550582231725359408128481117450284102701938521105559644622948954930381964428810975665933446128475648233786783165271201909145648566923460348610454326648213393607260249141273724587006606315588174881520920962829254091715364367892590360011330530548820466521384146951941511609433057270365759591953092186117381932611793105118548074462379962749567351885752724891227938183011949129833673362440656643086021394946395224737190702179860943702770539217176293176752384674818467669405132000568127145263560827785771342757789609173637178721468440901224953430146549585371050792279689258923542019956112129021960864034418159813629774771309960518707211349999998372978049951059731732816096318595024459455346908302642522308253344685035261931188171010003137838752886587533208381420617177669147303598253490428755468731159562863882353787593751957781857780532171226806613001927876611

### Tuples

In [117]:
@show () 		# empty tuple
@show (1,) 		# one element tuple
@show ("a", 1) 	# two element tuple
@show ('a', false)::Tuple{Char, Bool} # tuple type assertion
@show x = (1, 2, 3)
@show x[1] 		# first element
@show x[1:2] 	# (1, 2) (tuple)
# x[4] 		# bounds error
# x[1] = 1 	# error - tuple is not mutable
@show a, b = x 	# tuple unpacking a==1, b==2


() = ()
(1,) = (1,)
("a", 1) = ("a", 1)
('a', false)::Tuple{Char, Bool} = ('a', false)
x = (1, 2, 3) = (1, 2, 3)
x[1] = 1
x[1:2] = (1, 2)
(a, b) = x = (1, 2, 3)


(1, 2, 3)

In [ ]:
t = (3, 3.0)
typeof(t)

In [ ]:
k = (1, "k",  1//5)
typeof(k)

In [ ]:
v = collect(3:10)
v[7:end]

### Matrices

In [118]:
Array{Char}(undef, 2, 3, 4) 	# 2x3x4 array of Chars
@show Array{Any}(undef, 2, 3) 	# 2x3 array of Any
@show zeros(5) 				# vector of Float64 zeros
@show ones(Int64, 2, 1) 	# 2x1 array of Int64 ones
@show trues(3), falses(3) 	# tuple of vector of trues and of falses

@show x = range(1, stop=2, length=5)  # iterator having 5 equally spaced elements
@show collect(x) 	# converts iterator to vector
@show 1:10 			# iterable from 1 to 10
@show 1:2:10 		# iterable from 1 to 9 with 2 skip
@show reshape(1:12, 3, 4)	# 3x4 array filled with 1:12 values


Array{Any}(undef, 2, 3) = Any[#undef #undef #undef; #undef #undef #undef]
zeros(5) = [0.0, 0.0, 0.0, 0.0, 0.0]
ones(Int64, 2, 1) = [1; 1;;]
(trues(3), falses(3)) = (Bool[1, 1, 1], Bool[0, 0, 0])
x = range(1, stop = 2, length = 5) = 1.0:0.25:2.0
collect(x) = [1.0, 1.25, 1.5, 1.75, 2.0]
1:10 = 1:10
1:2:10 = 1:2:9
reshape(1:12, 3, 4) = [1 4 7 10; 2 5 8 11; 3 6 9 12]


3×4 reshape(::UnitRange{Int64}, 3, 4) with eltype Int64:
 1  4  7  10
 2  5  8  11
 3  6  9  12

In [119]:
Matrix

Matrix (alias for Array{T, 2} where T)

In [127]:
y = Matrix{Int64}(undef, 2, 3)

2×3 Matrix{Int64}:
               0  140703366427184  140703355355408
 140703355355408                0  140703355326736

In [128]:
m = zeros( 4,5)
m[1,3] = 66
m
# 1-based numbering 

4×5 Matrix{Float64}:
 0.0  0.0  66.0  0.0  0.0
 0.0  0.0   0.0  0.0  0.0
 0.0  0.0   0.0  0.0  0.0
 0.0  0.0   0.0  0.0  0.0

In [129]:
m[:,3] #array slicing

4-element Vector{Float64}:
 66.0
  0.0
  0.0
  0.0

In [136]:
a = reshape(1:12_000_000_000, 3_000, 4_000_000)




3000×4000000 reshape(::UnitRange{Int64}, 3000, 4000000) with eltype Int64:
    1  3001  6001   9001  12001  15001  18001  …  11999994001  11999997001
    2  3002  6002   9002  12002  15002  18002     11999994002  11999997002
    3  3003  6003   9003  12003  15003  18003     11999994003  11999997003
    4  3004  6004   9004  12004  15004  18004     11999994004  11999997004
    5  3005  6005   9005  12005  15005  18005     11999994005  11999997005
    6  3006  6006   9006  12006  15006  18006  …  11999994006  11999997006
    7  3007  6007   9007  12007  15007  18007     11999994007  11999997007
    8  3008  6008   9008  12008  15008  18008     11999994008  11999997008
    9  3009  6009   9009  12009  15009  18009     11999994009  11999997009
   10  3010  6010   9010  12010  15010  18010     11999994010  11999997010
   11  3011  6011   9011  12011  15011  18011  …  11999994011  11999997011
   12  3012  6012   9012  12012  15012  18012     11999994012  11999997012
   13  3013  6013   9013 

In [ ]:
a = reshape(1:12, 3, 4)
display(a[:, 3:end]) # 3x2 matrix
display(a[:, 1]) # 3 element vector
display(a[1, :]) # 4 element vector


### Data structures

In [137]:
mutable struct Point1
  x::Int 
  y::Float64
  meta
end
p = Point1(0, 0.0, "Origin")
@show p
@show p.x 		# access field
p.meta = 2		# change field value
@show fieldnames(typeof(p)) # get names of instance fields
@show fieldnames(Point1); 	# get names of type fields


p = Point1(0, 0.0, "Origin")
p.x = 0
fieldnames(typeof(p)) = (:x, :y, :meta)
fieldnames(Point1) = (:x, :y, :meta)


In [138]:
dump(:x)

Symbol x


In [139]:
dump(p)

Point1
  x: Int64 0
  y: Float64 0.0
  meta: Int64 2


In [ ]:
fieldnames(typeof(p))

In [140]:
dump(:a)

Symbol a


In [141]:
Base.@kwdef struct Point2
  x::Int64 = 1
  y::Float64 = 2.0
  meta
end
p2 = Point2(x=999, meta = "Origin")

Point2(999, 2.0, "Origin")

In [142]:
try 
    p2.x = 33333
catch e
    println(e)
end

ErrorException("setfield!: immutable struct of type Point2 cannot be changed")


In [143]:
using Parameters
@with_kw mutable struct Point3
  x::Int64 = 1
  y::Float64 = 2.0
  meta
end
p3 = Point3(x=999, meta = "Origin")
p3.x = 66
p3

Point3
  x: Int64 66
  y: Float64 2.0
  meta: String "Origin"


In [ ]:
Point3(;x=11,meta="ss")

### Dictionaries

In [144]:
x = Dict{Int, Float64}() 
x[5] = 66.6
x[7] = 99

x

Dict{Int64, Float64} with 2 entries:
  5 => 66.6
  7 => 99.0

In [ ]:
x2 = Dict{Any, Any}() 
x2[5] = 66.6
x2[7] = 99

x2

In [147]:
typeof(1=>5)

Pair{Int64, Int64}

In [148]:
y = Dict(1=>5.5, 2=>4.5) 

Dict{Int64, Float64} with 2 entries:
  2 => 4.5
  1 => 5.5

In [150]:
x = Dict{Int, Float64}() # empty dictionary mapping integers to floats
y = Dict(1=>5.5, 2=>4.5) 	# created dictionary
@show y[2] 					# get element
@show y[3] = 30.0 			# add element
@show haskey(y, 2) 			# check if key exists
@show keys(y), values(y) # iterators returning dictionary keys and values
@show delete!(y, 2)   # removing elements see also: pop!
@show get(y, 2, 777) # returns y[2] or 777 if not haskey(y,2)


y[2] = 4.5
y[3] = 30.0 = 30.0
haskey(y, 2) = true
(keys(y), values(y)) = ([2, 3, 1], [4.5, 30.0, 5.5])
delete!(y, 2) = Dict(3 => 30.0, 1 => 5.5)
get(y, 2, 777) = 777


777

### Text processing

In [152]:
x = 123
@show "$x + 3 = $(x+3)  3\$"  

"$(x) + 3 = $(x + 3)  3\$" = "123 + 3 = 126  3\$"


"123 + 3 = 126  3\$"

In [151]:
@show "Hi " * "there!" 		# concatenation
@show "Ho " ^ 3 			# multiplication
@show string("a= ", 123.3) 	# joining elements to text
@show occursin("CD","ABCD") 	# occurence
@show "\"\n\t\$" # C-like escaping, additionally escape \$ 
                          # escaping - similiar to Matlab, Python, R
x = 123
@show "$x + 3 = $(x+3)"  # $ is an interpolation operator
@show "\$199" # that is why you need escaping

r = r"A|B" # full support for regular expressions
@show occursin(r, "CD") # false, not found
@show m = match(r, "ACBD"); # first regexp match 


"Hi " * "there!" = "Hi there!"
"Ho " ^ 3 = "Ho Ho Ho "
string("a= ", 123.3) = "a= 123.3"
occursin("CD", "ABCD") = true
"\"\n\t\$" = "\"\n\t\$"
"$(x) + 3 = $(x + 3)" = "123 + 3 = 126"
"\$199" = "\$199"
occursin(r, "CD") = false
m = match(r, "ACBD") = RegexMatch("A")


In [ ]:

x = 6

tekst = "hello $x and $(x*x+2x)"

In [ ]:
str = raw"c:\windows\n"

In [ ]:
?@raw_str

### Functions

In [ ]:
f(x, y = 10) = x + y 
# for this function the default value of y is 10
@show f(3, 2) # 5 is returned
@show f(3)    # 13 is returned





In [155]:
function g(x::Int, y::Int) # limit arg type
  return y, x # tuple returned 
end

g(x::Int, y::Bool) = x * y # multiple dispatch
g(x, y) = x - y
methods(g) # list of methods for g



# 3 methods for generic function "g":
[1] g(x::Int64, y::Int64) in Main at In[155]:1
[2] g(x::Int64, y::Bool) in Main at In[155]:5
[3] g(x, y) in Main at In[155]:6

In [ ]:
function g(x::Int, y::Int) # limit arg type
  return y, x # tuple returned 
end

g(x::Int, y::Bool) = x * y # multiple dispatch

@show g(1,2)
@show g(1, true)


In [ ]:
methods(g)

In [ ]:
@show g(1,4)
@show g(1,true)
methods(g)

### Operators

In [156]:
[1 2] .< [2 1]

1×2 BitMatrix:
 1  0

In [ ]:
@show true || false # binary or operator (singeltons only)
@show 1 < 2 < 3     # condition chaining  is OK 
@show [1 2] .< [2 1] # vectorization via dot operator "."
@show a = 5
@show 2a + 2(a+1) # multiplication can be ommited 
@show x = [1 2 3]	  #matrix 1×3 Array{Int64,2}    
@show y = [1, 2, 3]  #matrix 3-elements Array{Int64,1}
# vectors are vecticar and are different concept than horizontal 1-row matrix
#x + y # error
@show x .+ y # 3x3 matrix, dimension broadcasting
@show x + y' # 1x3 matrix
@show x * y; # array multiplication, 1-element vector (not scalar)


In [ ]:
f(x,y) =  x<y ? x : y

In [ ]:
f(10,30)

In [ ]:
a=  [1,2,3]
b=  [0,5,6]

In [ ]:
f.(a,b)

In [ ]:
a .* b

### Simple demo

In [157]:
function calc_pi(n, T)
    # n is the number of replications
    # T is the result type
    s = one(T)
    f = one(T)
    for i::T in 1:n
        f *= i/(2i+1)
        s += f
    end
    2s
end

calc_pi (generic function with 1 method)

In [158]:
π
typeof(π)

Irrational{:π}

In [ ]:
π

In [159]:
for T in [Float16, Float64, BigFloat]
    display([calc_pi(2^n, T) for n in 1:10] .- big(π))
end

10-element Vector{BigFloat}:
 -0.2079989035897932384626433832795028841971693993751058209749445923078164062862089986280348253421170679821480865132823066470938446095505822317253594081284811174502841027019385211055596446229489549303819644288109756659334461284756482337867831652712019091456485669234603486104543266482133936072602491412737245870066063155881748815209209628292540917153643678925903600113305305488204665213841469519415116094330572703657595919530921861173819326117931051185480744623799627495673518857527248912279381830119491298336733624406566430860213949463952247371907021798609437027705392171762931767523846748184676694051320005681271452635608277857713427577896091736371787214684409012249534301465495853710507922796892589235420199561121290219608640344181598136297747713099605187072113499999983729780499510597317328160963185950244594553469083026425223082533446850352619311881710100031378387528865875332083814206171776691473035982534904287554687311595628638823537875937519577818577805321712268

10-element Vector{BigFloat}:
 -0.2082593202564601123709413133087237632750807763282308209749445923078164062862089986280348253421170679821480865132823066470938446095505822317253594081284811174502841027019385211055596446229489549303819644288109756659334461284756482337867831652712019091456485669234603486104543266482133936072602491412737245870066063155881748815209209628292540917153643678925903600113305305488204665213841469519415116094330572703657595919530921861173819326117931051185480744623799627495673518857527248912279381830119491298336733624406566430860213949463952247371907021798609437027705392171762931767523846748184676694051320005681271452635608277857713427577896091736371787214684409012249534301465495853710507922796892589235420199561121290219608640344181598136297747713099605187072113499999983729780499510597317328160963185950244594553469083026425223082533446850352619311881710100031378387528865875332083814206171776691473035982534904287554687311595628638823537875937519577818577805321712268

10-element Vector{BigFloat}:
 -0.2082593202564599051293100499461695508638360660417724876416112589744830729528756652947014920087837346488147531799489733137605112762172488983920260747951477841169507693686051877722263112896156215970486310954776423326001127951423149004534498319378685758123152335901270152771209933148800602739269158079403912536732729822548415481875876294959207583820310345592570266779971972154871331880508136186081782760997239370324262586197588527840485992784597717852147411290466294162340185524193915578946048496786157965003400291073233097526880616130618914038573688465276103694372058838429598434190513414851343360717986672347938119302274944524380094244562758403038453881351075678916200968132162520377174589463559255902086866227787956886275307010848264802964414379766271853738780166666650396447166177263983994827629852616911261220135749693091889749200113517019285978548376766698045054195532541998750480872838443358139702649201570954221353978262295305490204542604186244485244471988378934

In [160]:
calc_pi(10000, BigFloat)- π


-6.0148472990477424111570671204915732991858813376061110073057148507350874371409408482269328354981068960338262191434470046497592931812269527619778602745754937423049050933392734747261853408252801760528263129722994947486595565487290789682727478174850632185487405571372705831065092984312447990874820009403698936873093631844863439913077079426582030698297174415417847791529890565693654498100654664041982764790684775724637039781041560610745264726579307740388244540321092384479044633191442266732192798842336569003661060627510539439816682771784927758790793028660982828833269202258887216343178309238449487896363051442736778334268036614846812402568028871386286223003235953423972176667566417283874894341219636377474839890659563252271938838838068701563068188177644588369973253396086837857420917173165112696426257425082179411451781627071845863402866398254846051078307095471340595249085392244179142558853417242129013313457061818520812569279507102197199319991087007084859198695769821940123704767712853860809894703775

In [ ]:
setprecision(1000) do
    calc_pi(1000, BigFloat)-π
end

In [ ]:
setprecision(8000) do
    @show BigFloat(π)
    end;

In [161]:
[calc_pi(n, Rational) for n in 1:20]

20-element Vector{Rational{Int64}}:
                8//3
               44//15
               64//21
              976//315
            10816//3465
           141088//45045
            47104//15015
          2404096//765765
         45693952//14549535
         45701632//14549535
         80863232//25741485
       5256312832//1673196525
       3153846272//1003917915
     457311809536//145568097675
     833925152768//265447707525
    4725585805312//1504203675975
   14176771899392//4512611027925
  524540820979712//166966608033225
  104908189597696//33393321606645
 4301236281540608//1369126185872445

### Integration with other programming languages

In [ ]:
using PyCall
np = pyimport("numpy")



In [ ]:
a = np.zeros((4, 5), dtype="int32")
a

In [ ]:
a[1,1]=5
np.mean(a)

In [ ]:
b = py"{ (x,y):x*y for x in range(1,5) for y in range(1,3) }"
b

In [ ]:
using Distributions, DataFrames, Random
Random.seed!(0);
dat = permutedims(rand(MvNormal([1 0.75; 0.75 1]), 1000))
df = DataFrame(dat, :auto)


You need to have RCall for this demo together with R present in the operating system, hence this will be shown by the instructor only. 
However you could try installing it yourself:
```
using Pkg
pkg"add RCall"
```

In [ ]:
try
    using RCall
    @rlibrary ggplot2
    ggplot(df,aes(x=:x1,y=:x2)) + geom_point()
catch e; end

In [ ]:
try
    using RCall
    R"library(ggplot2)"
    R"ggplot($df,aes(x=x1,y=x2)) + geom_point()"
catch e; end

*Preparation of this workshop has been supported by the Polish National Agency for Academic Exchange under the Strategic Partnerships programme, grant number BPI/PST/2021/1/00069/U/00001.*

![SGH & NAWA](logo.png)